### ISSUE TITLE
Nan Embedding Wiki

### ISSUE THREAD

**Issue by snash4** [mengzaiqiao/CAN#1]
Hi, 
  The model works fine for the dataset that you have used. I tried it on Wiki dataset (another standard dataset), but it throws Nan Error.  The loss reaches to Nan on the first iteration. Could you please help me out to figure out this error.

**Comment by mengzaiqiao** [comment]
Hi Sheikh,

Thank you for your interest on my model. 

I have not tried our model on the Wiki Dataset. Could you please send me your preprocessed wiki dataset, so that I can debug it based on your dataset? My email is : zqmeng@aliyun.com
------------------------------------------------------

Best Regards,

Zaiqiao Meng
